# Generated by Django 2.0.4 on 2018-04-30 04:17

import apps.api.models
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
                ('calling_code', models.PositiveSmallIntegerField()),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('capital', models.CharField(max_length=75)),
                ('currency', djongo.models.fields.EmbeddedModelField(model_container=apps.api.models.Currency, null=True)),
                ('marker_latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('marker_longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('flag', models.ImageField(blank=True, upload_to='country_flags')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsBusinessExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('partner_countries', djongo.models.fields.ArrayModelField(model_container=apps.api.models.CountryDistribution, model_form_class=apps.api.models.CountryDistributionForm)),
                ('partner_countries_indicator', models.CharField(blank=True, max_length=30)),
                ('exported_items', djongo.models.fields.ArrayModelField(model_container=apps.api.models.GoodsDistribution, model_form_class=apps.api.models.GoodsDistributionForm)),
                ('exported_items_indicator', models.CharField(blank=True, max_length=30)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Business Exports',
                'verbose_name_plural': 'Country Details - Business Exports',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsBusinessFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('net_inflow', djongo.models.fields.ArrayModelField(model_container=apps.api.models.GenericRangeDistribution)),
                ('net_inflow_indicator', models.CharField(blank=True, max_length=30)),
                ('investor_countries', djongo.models.fields.ArrayModelField(model_container=apps.api.models.CountryDistribution, model_form_class=apps.api.models.CountryDistributionForm)),
                ('investor_countries_indicator', models.CharField(blank=True, max_length=30)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Business FDIs',
                'verbose_name_plural': 'Country Details - Business FDIs',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsBusinessFTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('associated_countries', models.ManyToManyField(blank=True, related_name='business_details', to='api.Country')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Business FTAs',
                'verbose_name_plural': 'Country Details - Business FTAs',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsBusinessInvestmentReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('reasons', djongo.models.fields.ArrayModelField(model_container=core.models.InfoMeta)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Investment Reasons',
                'verbose_name_plural': 'Country Details - Investment Reasons',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsBusinessInvestmentSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Investment Sectors',
                'verbose_name_plural': 'Country Details - Investment Sectors',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsDemographicsAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('median', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distribution', djongo.models.fields.ArrayModelField(model_container=apps.api.models.GenericRangeDistribution)),
                ('distribution_indicator', models.CharField(blank=True, max_length=30)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Age Demographics',
                'verbose_name_plural': 'Country Details - Age Demographics',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('gdp_total', models.DecimalField(decimal_places=2, max_digits=24)),
                ('gdp_per_capita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unemployment_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('political_stability_index', djongo.models.fields.EmbeddedModelField(model_container=apps.api.models.PoliticalStability, null=True)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Economy',
                'verbose_name_plural': 'Country Details - Economy',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('area', models.BigIntegerField()),
                ('population', models.BigIntegerField()),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - General',
                'verbose_name_plural': 'Country Details - General',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsMobileUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('total_phones', models.BigIntegerField()),
                ('distribution', djongo.models.fields.ArrayModelField(model_container=apps.api.models.GoodsDistribution, model_form_class=apps.api.models.GoodsDistributionForm)),
                ('distribution_indicator', models.CharField(blank=True, max_length=30)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Mobile Usage',
                'verbose_name_plural': 'Country Details - Mobile Usage',
            },
        ),
        migrations.CreateModel(
            name='CountryDetailsServiceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('service_type', models.CharField(choices=[('social-media', 'Social Media'), ('e-commerce', 'E-Commerce')], max_length=30)),
                ('distribution', djongo.models.fields.ArrayModelField(model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm)),
                ('distribution_indicator', models.CharField(blank=True, max_length=30)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Service Usage',
                'verbose_name_plural': 'Country Details - Service Usage',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='goods_logos')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='goods_logos')),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religions',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='service_logos')),
                ('company', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Sector')),
            ],
            options={
                'verbose_name': 'Sub-Sector',
                'verbose_name_plural': 'Sub-Sectors',
            },
        ),
        migrations.AddField(
            model_name='countrydetailsgeneral',
            name='languages',
            field=models.ManyToManyField(blank=True, to='api.Language'),
        ),
        migrations.AddField(
            model_name='countrydetailsgeneral',
            name='religions',
            field=models.ManyToManyField(blank=True, to='api.Religion'),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessinvestmentsectors',
            name='key_sectors',
            field=models.ManyToManyField(blank=True, to='api.SubSector'),
        ),
    ]
