# Generated by Django 2.0.4 on 2018-05-07 08:09

import apps.api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('associated_countries', models.ManyToManyField(blank=True, related_name='policy_countries', to='api.Country')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='CountryPolicyLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('color', models.CharField(max_length=7)),
                ('width', models.FloatField()),
                ('waypoints', djongo.models.fields.ArrayModelField(model_container=apps.api.models.GeoCoordinates)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='api.CountryPolicy')),
            ],
            options={
                'verbose_name': 'Policy Line',
                'verbose_name_plural': 'Policy Lines',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('company', models.CharField(blank=True, max_length=75)),
                ('description', models.TextField(blank=True)),
                ('source_ip', models.CharField(blank=True, max_length=50)),
                ('lead_owner', models.CharField(default='weiliang.ho@goldenequator.com', max_length=75)),
                ('lead_source', models.CharField(default='Insights', max_length=50)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
