# Generated by Django 2.0.4 on 2018-05-08 07:49

import apps.api.models
import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_countrypolicy_countrypolicyline_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(blank=True, max_length=85, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='generic_images')),
            ],
            options={
                'verbose_name': 'Generic Image',
                'verbose_name_plural': 'Generic Images',
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='logo',
            field=models.ImageField(blank=True, upload_to='sector_logos'),
        ),
        migrations.AddField(
            model_name='subsector',
            name='logo',
            field=models.ImageField(blank=True, upload_to='subsector_logos'),
        ),
    ]
