# Generated by Django 2.0.4 on 2018-05-08 08:16

import apps.api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180508_0749'),
    ]

    operations = []
