# Generated by Django 2.0.4 on 2018-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180508_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetailseconomy',
            name='gdp_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24),
        ),
    ]
