# Generated by Django 2.0.4 on 2018-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='exported_items_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='partner_countries_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='investor_countries_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='net_inflow_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsdemographicsage',
            name='distribution_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='distribution_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsserviceusage',
            name='distribution_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
