# Generated by Django 2.0.4 on 2018-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180511_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypolicyline',
            name='countries',
            field=models.ManyToManyField(blank=True, to='api.Country'),
        ),
        migrations.AddField(
            model_name='countrypolicyline',
            name='region',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
