# Generated by Django 2.0.4 on 2018-05-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180516_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='exported_items_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='partner_countries_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='investor_countries_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='net_inflow_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsdemographicsage',
            name='distribution_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='distribution_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsserviceusage',
            name='distribution_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
    ]
