# Generated by Django 2.0.4 on 2018-05-24 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180522_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPolicyRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('region', models.CharField(max_length=75)),
                ('region_latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('region_longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('region_zoom', models.FloatField(default=4.0)),
                ('countries', models.ManyToManyField(blank=True, to='api.Country')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='api.CountryPolicy')),
            ],
            options={
                'verbose_name': 'Policy Region',
                'verbose_name_plural': 'Policy Regions',
            },
        ),
        migrations.RemoveField(
            model_name='countrypolicyline',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='countrypolicyline',
            name='region',
        ),
        migrations.AddField(
            model_name='countrypolicyline',
            name='route_type',
            field=models.CharField(choices=[('land', 'Land Route'), ('sea', 'Sea Route'), ('combined', 'Land & Sea Route')], default='land', max_length=50),
        ),
    ]
