# Generated by Django 2.0.4 on 2018-06-05 06:15

import apps.api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180530_0143'),
    ]

    operations = []
