# Generated by Django 2.0.4 on 2018-06-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180605_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydetailsgeneral',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='countrydetailsgeneral',
            name='religions',
        ),
    ]
