# Generated by Django 2.0.4 on 2018-08-28 02:18

import apps.api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180605_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypolicy',
            name='name',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrypolicy',
            name='slug',
            field=models.CharField(default='', max_length=85),
            preserve_default=False,
        ),
    ]
