# Generated by Django 2.0.4 on 2018-08-28 07:39

import apps.api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180828_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypolicy',
            name='title',
        ),
        migrations.AlterField(
            model_name='countrypolicy',
            name='slug',
            field=models.CharField(blank=True, max_length=85, unique=True),
        ),
    ]
