# Generated by Django 2.0.4 on 2018-09-25 07:47

import apps.api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180828_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='hs92_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='goods',
            name='parent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='api.Goods'),
            preserve_default=False,
        ),
    ]
