# Generated by Django 2.0.4 on 2018-11-05 08:44

import apps.api.models
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180925_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetailsBusinessImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('partner_countries', djongo.models.fields.ArrayModelField(model_container=apps.api.models.CountryDistribution, model_form_class=apps.api.models.CountryDistributionForm)),
                ('partner_countries_indicator', models.CharField(blank=True, max_length=75)),
                ('partner_countries_year', models.CharField(blank=True, max_length=20)),
                ('partner_countries_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('imported_items', djongo.models.fields.ArrayModelField(model_container=apps.api.models.GoodsDistribution, model_form_class=apps.api.models.GoodsDistributionForm)),
                ('imported_items_indicator', models.CharField(blank=True, max_length=75)),
                ('imported_items_year', models.CharField(blank=True, max_length=20)),
                ('imported_items_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Business Imports',
                'verbose_name_plural': 'Country Details - Business Imports',
            },
        ),
    ]
