# Generated by Django 2.0.4 on 2018-11-15 12:50

import apps.api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181105_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetailsFTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('coverage_type', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('goods-and-services', 'Goods & Services')], max_length=20)),
                ('trade_descriptions', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.DescriptionDistribution)),
                ('trade_links', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.LinksDistribution)),
                ('industry_country_benefits', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.CountryIndustryDistribution, model_form_class=apps.api.models.CountryIndustryDistributionForm)),
            ],
            options={
                'verbose_name': 'Country Details - FTA',
                'verbose_name_plural': 'Country Details - FTAs',
            },
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='industry_sector_logos')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.IndustrySector')),
            ],
            options={
                'verbose_name': 'Industry Sector',
                'verbose_name_plural': 'Industry Sectors',
            },
        ),
        migrations.CreateModel(
            name='MobileWebActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='activity_logos')),
            ],
            options={
                'verbose_name': 'Mobile/Web Activity',
                'verbose_name_plural': 'Mobile/Web Activities',
            },
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='partner_countries_products',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.CountryGoodsDistribution, model_form_class=apps.api.models.CountryGoodsDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='partner_countries_products_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='partner_countries_products_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='partner_countries_products_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='total_yearly_exports',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.YearDistribution),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='top_sectors',
            field=djongo.models.fields.ArrayModelField(blank=True, default=[], model_container=apps.api.models.IndustrySectorDistribution, model_form_class=apps.api.models.IndustrySectorDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='top_sectors_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='top_sectors_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='top_sectors_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='yearly_net_inflow',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.YearDistribution),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessimport',
            name='partner_countries_products',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.CountryGoodsDistribution, model_form_class=apps.api.models.CountryGoodsDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessimport',
            name='partner_countries_products_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessimport',
            name='partner_countries_products_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessimport',
            name='partner_countries_products_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessimport',
            name='total_yearly_imports',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.YearDistribution),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessinvestmentreasons',
            name='links',
            field=djongo.models.fields.ArrayModelField(blank=True, default=[], model_container=apps.api.models.LinksDistribution),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessinvestmentsectors',
            name='key_industry_sectors',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.IndustrySectorDescription, model_form_class=apps.api.models.IndustrySectorDescriptionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailseconomy',
            name='economy_details_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailseconomy',
            name='gdp_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_activities',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.MobileActivityDistribution, model_form_class=apps.api.models.MobileActivityDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_activities_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_activities_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_activities_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_apps',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.AppDistribution, model_form_class=apps.api.models.AppDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_apps_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_apps_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_messaging_apps',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_messaging_apps_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_messaging_apps_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='top_messaging_apps_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='traffic_distribution',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=apps.api.models.GoodsDistribution, model_form_class=apps.api.models.GoodsDistributionForm),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='traffic_distribution_indicator',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='traffic_distribution_value_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='traffic_distribution_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='countrydetailsserviceusage',
            name='service_type',
            field=models.CharField(choices=[('social-media', 'Social Media'), ('e-commerce', 'E-Commerce'), ('digital-payments', 'Digital Payments')], max_length=30),
        ),
        migrations.AlterField(
            model_name='countrypolicy',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='countrypolicy',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genericimage',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='genericimage',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='religion',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='countrydetailsfta',
            name='associated_countries',
            field=models.ManyToManyField(blank=True, to='api.Country'),
        ),
    ]
