# Generated by Django 2.0.4 on 2018-11-15 23:13

import apps.api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181115_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetailsbusinessfdi',
            name='net_inflow',
            field=djongo.models.fields.ArrayModelField(model_container=apps.api.models.GenericRangeDistribution, model_form_class=apps.api.models.GenericRangeDistributionForm),
        ),
        migrations.AlterField(
            model_name='countrydetailsdemographicsage',
            name='distribution',
            field=djongo.models.fields.ArrayModelField(model_container=apps.api.models.GenericRangeDistribution, model_form_class=apps.api.models.GenericRangeDistributionForm),
        ),
    ]
