# Generated by Django 2.0.4 on 2018-11-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181115_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydetailsbusinessfdi',
            name='net_inflow',
        ),
    ]
