# Generated by Django 2.0.4 on 2019-01-09 08:16

import apps.api.models
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_countrydetailsbusinessfdi_net_inflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetailsServicesUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('social_media_distribution', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm)),
                ('social_media_distribution_indicator', models.CharField(blank=True, max_length=75)),
                ('social_media_distribution_year', models.CharField(blank=True, max_length=20)),
                ('social_media_distribution_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('social_media_insights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('social_media_gender_profile', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceGenderDistribution, model_form_class=apps.api.models.ServiceGenderDistributionForm)),
                ('social_media_gender_profile_indicator', models.CharField(blank=True, max_length=75)),
                ('social_media_gender_profile_year', models.CharField(blank=True, max_length=20)),
                ('social_media_gender_profile_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('social_media_mobile_usage', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm)),
                ('social_media_mobile_usage_indicator', models.CharField(blank=True, max_length=75)),
                ('social_media_mobile_usage_year', models.CharField(blank=True, max_length=20)),
                ('social_media_mobile_usage_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('social_media_daily_platform_usage', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm)),
                ('social_media_daily_platform_usage_indicator', models.CharField(blank=True, max_length=75)),
                ('social_media_daily_platform_usage_year', models.CharField(blank=True, max_length=20)),
                ('social_media_daily_platform_usage_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('ecommerce_distribution', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm)),
                ('ecommerce_distribution_indicator', models.CharField(blank=True, max_length=75)),
                ('ecommerce_distribution_year', models.CharField(blank=True, max_length=20)),
                ('ecommerce_distribution_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('ecommerce_penetration', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('ecommerce_penetration_indicator', models.CharField(blank=True, max_length=255)),
                ('ecommerce_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=24)),
                ('ecommerce_insights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('digital_payments_distribution', djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm)),
                ('digital_payments_distribution_indicator', models.CharField(blank=True, max_length=75)),
                ('digital_payments_distribution_year', models.CharField(blank=True, max_length=20)),
                ('digital_payments_distribution_value_type', models.CharField(choices=[('percentage', 'Percentage'), ('absolute', 'Absolute')], default='percentage', max_length=20)),
                ('fin_account_ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('credit_card_ownership', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('digital_transactions_last_year', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('digital_payments_insights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('highlights', djongo.models.fields.ArrayModelField(blank=True, model_container=core.models.InfoMeta)),
                ('extra_comments', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Country')),
            ],
            options={
                'verbose_name': 'Country Details - Services Usage',
                'verbose_name_plural': 'Country Details - Services Usage',
            },
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessexport',
            name='trade_to_gdp_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessfdi',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessimport',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessinvestmentreasons',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsbusinessinvestmentsectors',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsdemographicsage',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailseconomy',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsfta',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsfta',
            name='highlights',
            field=djongo.models.fields.ArrayModelField(blank=True, default=[], model_container=core.models.InfoMeta),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydetailsgeneral',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsmobileusage',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='countrydetailsserviceusage',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
    ]
