# Generated by Django 2.0.4 on 2019-01-11 10:25

import apps.api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190109_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetailsbusinessexport',
            name='total_yearly_exports',
            field=djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.YearDistribution),
        ),
        migrations.AlterField(
            model_name='countrydetailsbusinessimport',
            name='total_yearly_imports',
            field=djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.YearDistribution),
        ),
    ]
