# Generated by Django 2.0.4 on 2019-01-15 06:42

import apps.api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190111_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydetailsmobileusage',
            name='top_activities',
            field=djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.MobileActivityDistribution, model_form_class=apps.api.models.MobileActivityDistributionForm),
        ),
        migrations.AlterField(
            model_name='countrydetailsmobileusage',
            name='top_apps',
            field=djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.AppDistribution, model_form_class=apps.api.models.AppDistributionForm),
        ),
        migrations.AlterField(
            model_name='countrydetailsmobileusage',
            name='top_messaging_apps',
            field=djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.ServiceDistribution, model_form_class=apps.api.models.ServiceDistributionForm),
        ),
        migrations.AlterField(
            model_name='countrydetailsmobileusage',
            name='traffic_distribution',
            field=djongo.models.fields.ArrayModelField(blank=True, model_container=apps.api.models.GoodsDistribution, model_form_class=apps.api.models.GoodsDistributionForm),
        ),
    ]
