# Generated by Django 2.0.4 on 2018-05-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelhistory',
            options={'ordering': ['-id'], 'verbose_name': 'Model History', 'verbose_name_plural': 'Model History'},
        ),
    ]
