# Generated by Django 3.1.7 on 2021-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_user', '0002_docuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='docuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
