# Generated by Django 3.1.7 on 2021-10-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_user', '0004_auto_20211014_0818'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='docuser',
            table='document_user',
        ),
    ]
